TrajectoryPlannerROS:
  max_vel_x: 0.6
  min_vel_x: 0.05
  max_rotational_vel: 0.1
  min_in_place_rotational_vel: 0.01
  escape_vel: -0.1

  acc_lim_theta: 0.05
  acc_lim_x: 0.2
  acc_lim_y: 0.2

  holonomic_robot: false
  meter_scoring: true
