obstacle_range: 2.5
raytrace_range: 10.0
footprint: [[0.5, 0], [0, 0.5],[-0.5, 0],[0, -0.5]]
inflation_radius: 0.55

transform_tolerance: 5
update_frequency: 5.0

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: laserSensors/sensor0, data_type: LaserScan, topic: dpl/hal/laser/sensor0/LaserScan, marking: true, clearing: true}