obstacle_range: 2.0
raytrace_range: 5.0
footprint: [[0.5190, 0], [0, 0.4150],[-0.5190, 0],[0, -0.4150]]

transform_tolerance: 0.5
update_frequency: 5.0
publish_frequency: 3.0

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: laserSensors/sensor0, data_type: LaserScan, topic: dpl/hal/laser/sensor0/LaserScan, marking: true, clearing: true}